language: cpp

compiler:
  - gcc
  - clang
  
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libgtest-dev
  - cd /usr/src/gtest && sudo cmake . && sudo make && sudo mv libg* /usr/lib

before_script:
  - cd $TRAVIS_BUILD_DIR
  - mkdir build
  - cd build
  - cmake ..
  
script:
  - make
  - ./test/runTests